# Generated by Django 2.2.5 on 2019-09-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apps_id', models.IntegerField(verbose_name='应用ID号')),
                ('business_name', models.CharField(max_length=50, verbose_name='业务线名称')),
                ('project_name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('project_envprofile', models.CharField(max_length=20, null=True, verbose_name='项目运行环境')),
                ('project_repo_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='git仓库地址')),
                ('project_kube_service', models.CharField(max_length=150, null=True, verbose_name='应用kubernetes服务名称')),
                ('project_kube_namespace', models.CharField(max_length=50, null=True, verbose_name='应用所属kubernetes命名空间')),
                ('project_start_cmdline', models.CharField(max_length=255, null=True, verbose_name='应用启动指令')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='其他说明内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目资产表',
                'verbose_name_plural': '项目资产表',
                'db_table': 'ops_project_assets',
                'permissions': (('can_read_project_assets', '读取产品线权限'), ('can_change_project_assets', '更改产品线权限'), ('can_add_project_assets', '添加产品线权限'), ('can_delete_project_assets', '删除产品线权限')),
            },
        ),
    ]
