# Generated by Django 2.2.5 on 2019-09-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_assets',
            name='apps_id',
            field=models.IntegerField(unique=True, verbose_name='应用ID号'),
        ),
    ]
